import uuid
from datetime import datetime, timezone
from typing import Dict, Any

def build_spec_output(pattern: Dict[str, Any], answers: Dict[str, Any], stack: Dict[str, Any], custom_requirements: str = "") -> Dict[str, Any]:
    """
    Constructs the formal OneShot .spec dictionary and markdown prompt.
    """
    spec_id = f"spec_{uuid.uuid4().hex[:12]}"
    timestamp = datetime.now(timezone.utc).isoformat()
    
    spec = {
        "oneshot_version": "1.0",
        "spec_id": spec_id,
        "generated_at": timestamp,
        "system": pattern.get("name", "Custom System"),
        "pattern_id": pattern.get("id", "custom_pattern"),
        "category": pattern.get("category", "general"),
        "confidence": pattern.get("confidence_score", 0.95),
        "data_models": pattern.get("data_models", {}),
        "user_configuration": answers,
        "technology_stack": stack,
        "known_constraints": pattern.get("known_constraints", {}),
        "failure_modes_to_avoid": pattern.get("known_failure_modes", []),
        "custom_requirements": custom_requirements if custom_requirements else None,
        "uncertainty_zones": [],
        "generated_by": "OneShot Precision Engine (sudolaps.top/oneshot)"
    }
    
    # Format markdown prompt for direct copy to Claude / GPT / Cursor / Windsurf
    failure_modes_md = "\n".join([f"- ⚠️ **{fm}**" for fm in pattern.get("known_failure_modes", [])])
    
    # Format data models in clear SQL / schema table breakdown
    models_breakdown = []
    for model_name, model_info in pattern.get("data_models", {}).items():
        table_name = model_info.get("table", model_name)
        fields = model_info.get("fields", [])
        field_strs = [f"  - `{f.get('name')}` ({f.get('type')})" + (" [PRIMARY KEY]" if f.get('primary') else "") + (" [UNIQUE]" if f.get('unique') else "") for f in fields]
        indexes = model_info.get("indexes", [])
        indexes_str = f"  - Indexes: `{', '.join(indexes)}`" if indexes else ""
        
        models_breakdown.append(f"### Table: `{table_name}`\n" + "\n".join(field_strs) + (f"\n{indexes_str}" if indexes_str else ""))

    data_models_md = "\n\n".join(models_breakdown) if models_breakdown else str(pattern.get("data_models", {}))
    
    choices_md = "\n".join([f"- **{k}**: `{v}`" for k, v in answers.items()]) if answers else "Default verified settings"
    
    spec_instruction = f"""# OneShot Precision Specification: {pattern.get('name', 'Custom System')}
> Generated by OneShot Spec Engine — Zero ambiguity, first-time precision.
> Spec ID: `{spec_id}` | Pattern: `{pattern.get('id')}`

You are an expert software engineer implementing a production-grade system based on this verified OneShot specification.
Follow every data model, configuration parameter, and constraint strictly without improvising unproven deviations.

---

## 1. System Target
- **System**: {pattern.get('name')}
- **Category**: {pattern.get('category')}
- **Target Stack**: Backend: **{stack.get('backend', 'Python')}**, Database: **{stack.get('database', 'PostgreSQL')}**, Cache: **{stack.get('cache', 'Redis')}**, Frontend: **{stack.get('frontend', 'React / Vanilla')}**

## 2. Configuration & Architecture Choices
{choices_md}

## 3. Database Models & Schema
{data_models_md}

## 4. System Constraints & Performance
- **Latency / Performance Limits**: {pattern.get('known_constraints', {})}
- **Zero-Tolerance Quality Gates**: Complete test coverage, atomic database transactions, parameterized queries.

## 5. Critical Failure Modes to Avoid (Strict Anti-Patterns)
{failure_modes_md}

## 6. Implementation Directive
Implement complete, robust, type-annotated, runnable code for this system. Include data models, migrations, service layer, repository/query layer, API routes, authentication/authorization checks, and unit tests. Do not leave placeholder comments. Build it correctly the first time.
"""

    clean_name = pattern.get('id', 'system').replace('-', '_')
    date_str = datetime.now().strftime('%Y%m%d')
    filename = f"{clean_name}_{date_str}.spec"

    return {
        "spec": spec,
        "spec_instruction": spec_instruction.strip(),
        "filename": filename
    }
